// src/renderer/components/titlebar/Titlebar.tsx
import React from 'react';
import './Titlebar.css';
const electron = window.require('electron');

export interface ITitlebarProps {}
export interface ITitlebarState {}
export default class Titlebar extends React.Component<
  ITitlebarProps,
  ITitlebarState
> {
  public constructor(props: ITitlebarProps) {
    super(props);
  }
  private close() {
    electron.ipcRenderer.send('pasco/close');
  }
  private minimize() {
    electron.ipcRenderer.send('pasco/minimize');
  }
  private maximizeRestore() {
    electron.ipcRenderer.send('pasco/maximize');
  }
  private onDoubleClick() {
    electron.ipcRenderer.send('pasco/maximize');
  }
  render() {
    return (
      <header id="titlebar" className="titlebar">
        <div className="window_control_row">
          <div
            className="window_spacer"
            onDoubleClick={() => console.log('WTF')}
          ></div>
          <div className="window_control_button_wrapper">
            <button
              className="window_control_button"
              onClick={this.minimize.bind(this)}
            >
              <img
                className="window_control_icon"
                src={require('../../../images/icons/minimize.png')}
                alt="Logo"
              />
            </button>
            <button
              className="window_control_button"
              onClick={this.maximizeRestore.bind(this)}
            >
              <img
                className="window_control_icon"
                src={require('../../../images/icons/maximize.png')}
                alt="Logo"
              />
            </button>
            <button
              className="window_control_button window_control_button_close"
              onClick={this.close.bind(this)}
            >
              <img
                className="window_control_icon"
                src={require('../../../images/icons/close.png')}
                alt="Logo"
              />
            </button>
          </div>
        </div>
      </header>
    );
  }
}

// src/app/components/titlebar/titlebar.component.ts
import { Component, OnInit } from '@angular/core';
import { ElectronService } from '../../core/services/electron/electron.service';

@Component({
  selector: 'pasco-titlebar',
  templateUrl: './titlebar.component.html',
  styleUrls: ['./titlebar.component.scss']
})
export class TitlebarComponent implements OnInit {
  private animationId;
  private mouseX;
  private mouseY;
  private currentMouseButtonDown;
  private framesMoved;


  constructor(private electron: ElectronService) {
    this.framesMoved = 0;
  }

  ngOnInit(): void {
  }
  private titleBarMouseDown(e) {
    this.mouseX = e.clientX;
    this.mouseY = e.clientY;
    document.addEventListener('mouseup', this.titleBarMouseUp.bind(this));
    document.addEventListener('mousemove', this.mouseMove.bind(this));
    requestAnimationFrame(this.moveWindow.bind(this, this.electron.ipcRenderer));
    cancelAnimationFrame(this.animationId);
    this.framesMoved = 0;
  }
  private titleBarMouseUp(e) {
    this.electron.ipcRenderer.send('windowMoved');
    document.removeEventListener('mouseup', this.titleBarMouseUp.bind(this));
    cancelAnimationFrame(this.animationId);
  }
  private moveWindow(ipcHandler) {
    ipcHandler.send('windowMoving', { windowId: 0, mouseX: this.mouseX, mouseY: this.mouseY });
    this.animationId = requestAnimationFrame(() => this.moveWindow(ipcHandler));
    this.framesMoved++;
  }
  private mouseMove(e) {
    this.currentMouseButtonDown = e.buttons !== undefined ? e.buttons : e.which;
  }
  private titleBarDoubleClick() {
    this.maximizeRestore();
  }
  private close() {
    this.electron.ipcRenderer.send('pasco/close');
  }
  private minimize() {
    this.electron.ipcRenderer.send('pasco/minimize');
  }
  private maximizeRestore() {
    this.electron.ipcRenderer.send('pasco/maximize');
  }
  private onDoubleClick() {
    this.electron.ipcRenderer.send('pasco/maximize');
  }
}

<header class="titlebar">
  <div class="tab-bar">
    <pasco-tab-bar></pasco-tab-bar>
  </div>
  <div class="nav-bar">
    <pasco-navigation-bar></pasco-navigation-bar>
  </div>
  <div class="window_control_row" [style.visibility]="showWindowControls ? 'visible' : 'hidden'"
    (dblclick)="titleBarDoubleClick()" (mousedown)="titleBarMouseDown($event)">
    <div class="window_spacer"></div>
    <div class="window_control_button_wrapper">
      <button class="window_control_button" (click)="minimize()">
        <img class="window_control_icon" src="../../assets/icons/minimize.png" alt="Minimize" />
      </button>
      <button class="window_control_button" (click)="maximizeRestore()">
        <img class="window_control_icon" src="../../assets/icons/maximize.png" alt="Maximize" />
      </button>
      <button class="window_control_button window_control_button_close" (click)="close()">
        <img class="window_control_icon" src="../../assets/icons/close.png" alt="Close" />
      </button>
    </div>
  </div>
</header>
